# Generated by Django 5.2.1 on 2025-06-09 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nutricionista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('crn', models.CharField(max_length=20, unique=True)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('sexo', models.CharField(max_length=1)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=150)),
            ],
        ),
    ]
